kind: Service
apiVersion: v1
metadata:
  name: doto-svc
  namespace: todo
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30081
  type: NodePort